#pragma once

#include <stdint.h>

typedef struct {
	uint8_t drive2 : 4;
	uint8_t drive1 : 4;
} floppy_register_t;

enum {
	FLOPPY_NO_DRIVE,
	FLOPPY_360_KB,
	FLOPPY_1_2_MB,
	FLOPPY_720_KB,
	FLOPPY_1_44_MB,
	FLOPPY_2_MB,
};

enum {
	FLOPPY_REG_STATUS_A = 0x3f0,
	FLOPPY_REG_STATUS_B,
	FLOPPY_REG_OUTPUT,
	FLOPPY_REG_TAPE_DRIVE,
	FLOPPY_REG_STATUS,
	FLOPPY_REG_DATARATE = 0x3f4,
	FLOPPY_REG_DATA,
	FLOPPY_REG_INPUT = 0x3f7,
	FLOPPY_REG_CONFIGURATION = 0x3f7,
};

enum {
	FLOPPY_CMD_READ_TRACK = 2,
	FLOPPY_CMD_PARAMETERS,
	FLOPPY_CMD_STATUS,
	FLOPPY_CMD_WRITE,
	FLOPPY_CMD_READ,
	FLOPPY_CMD_CALIBRATE,
	FLOPPY_CMD_SENSE_IRQ, // this ack?
	FLOPPY_CMD_WRITE_DELETED_SECTOR,
	FLOPPY_CMD_READ_ID,
	FLOPPY_CMD_READ_DELETED_SECTOR = 12,
	FLOPPY_CMD_FORMAT_TRACK,
	FLOPPY_CMD_DUMP,
	FLOPPY_CMD_SEEK,
	FLOPPY_CMD_VERSION,
	FLOPPY_CMD_SCAN,
	FLOPPY_CMD_PERPENDICULARISE, // yeah
	FLOPPY_CMD_CONFIGURE,
	FLOPPY_CMD_LOCK,
	FLOPPY_CMD_VERIFY = 22,
	FLOPPY_CMD_SCAN_LOW = 25,
	FLOPPY_CMD_SCAN_HIGH = 29,
	FLOPPY_CMD_SKIP = 0x20,
	FLOPPY_CMD_DENSITY = 0x40,
	FLOPPY_CMD_MULTITRACK = 0x80,
};

enum {
	FLOPPY_OUTPUT_DRIVE0 = 0,
	FLOPPY_OUTPUT_DRIVE1 = 1,
	FLOPPY_OUTPUT_DRIVE2 = 2,
	FLOPPY_OUTPUT_DRIVE3 = 3,
	FLOPPY_OUTPUT_RESET = 4,
	FLOPPY_OUTPUT_DMA = 8,
	FLOPPY_OUTPUT_DRIVE0_MOTOR = 16,
	FLOPPY_OUTPUT_DRIVE1_MOTOR = 32,
	FLOPPY_OUTPUT_DRIVE2_MOTOR = 64,
	FLOPPY_OUTPUT_DRIVE3_MOTOR = 128,
};